// Code generated by "stringer -type=Status"; DO NOT EDIT.

package jobs

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Init-1]
	_ = x[Accepted-2]
	_ = x[NoAvailableWorkers-3]
	_ = x[QueueFull-4]
	_ = x[Error-5]
	_ = x[Complete-6]
}

const _Status_name = "UnknownInitAcceptedNoAvailableWorkersQueueFullErrorComplete"

var _Status_index = [...]uint8{0, 7, 11, 19, 37, 46, 51, 59}

func (i Status) String() string {
	if i < 0 || i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
