@emulatorCustodyAccount = 0x0000000000000000

### List all enabled fungible tokens
GET http://localhost:3000/v1/fungible-tokens
content-type: application/json

### Get accounts tokens for admin account
GET http://localhost:3000/v1/accounts/{{$dotenv ADMIN_ADDRESS}}/fungible-tokens HTTP/1.1
content-type: application/json

### Get FlowToken details for admin account
GET http://localhost:3000/v1/accounts/{{$dotenv ADMIN_ADDRESS}}/fungible-tokens/flow-token HTTP/1.1
content-type: application/json

### Get FUSD details for admin account
GET http://localhost:3000/v1/accounts/{{$dotenv ADMIN_ADDRESS}}/fungible-tokens/fusd HTTP/1.1
content-type: application/json

### Create a FlowToken withdrawal from admin to custody account
POST http://localhost:3000/v1/accounts/{{$dotenv ADMIN_ADDRESS}}/fungible-tokens/flow-token/withdrawals HTTP/1.1
content-type: application/json

{
  "recipient":"{{emulatorCustodyAccount}}",
  "amount":"1.0"
}

### Create a FUSD withdrawal from admin to custody account
POST http://localhost:3000/v1/accounts/{{$dotenv ADMIN_ADDRESS}}/fungible-tokens/fusd/withdrawals HTTP/1.1
content-type: application/json

{
  "recipient":"{{emulatorCustodyAccount}}",
  "amount":"1.0"
}

### List FlowToken withdrawals for admin account
GET http://localhost:3000/v1/accounts/{{$dotenv ADMIN_ADDRESS}}/fungible-tokens/flow-token/withdrawals HTTP/1.1
content-type: application/json

### List FUSD withdrawals for admin account
GET http://localhost:3000/v1/accounts/{{$dotenv ADMIN_ADDRESS}}/fungible-tokens/fusd/withdrawals HTTP/1.1
content-type: application/json

### Get FlowToken withdrawal details for admin account
GET http://localhost:3000/v1/accounts/{{$dotenv ADMIN_ADDRESS}}/fungible-tokens/flow-token/withdrawals/<transaction_id> HTTP/1.1
content-type: application/json

### Setup FUSD on emulator for admin account
POST http://localhost:3000/v1/accounts/{{$dotenv ADMIN_ADDRESS}}/fungible-tokens/fusd HTTP/1.1
content-type: application/json



### Get accounts tokens for custody account
GET http://localhost:3000/v1/accounts/{{emulatorCustodyAccount}}/fungible-tokens HTTP/1.1
content-type: application/json

### Get FlowToken details for custody account
GET http://localhost:3000/v1/accounts/{{emulatorCustodyAccount}}/fungible-tokens/flow-token HTTP/1.1
content-type: application/json

### Get FUSD details for custody account
GET http://localhost:3000/v1/accounts/{{emulatorCustodyAccount}}/fungible-tokens/fusd HTTP/1.1
content-type: application/json

### Create a FlowToken withdrawal from custody to admin account
POST http://localhost:3000/v1/accounts/{{emulatorCustodyAccount}}/fungible-tokens/flow-token/withdrawals HTTP/1.1
content-type: application/json

{
  "recipient":"{{$dotenv ADMIN_ADDRESS}}",
  "amount":"1.0"
}

### Create a FUSD withdrawal from custody to admin account
POST http://localhost:3000/v1/accounts/{{emulatorCustodyAccount}}/fungible-tokens/fusd/withdrawals HTTP/1.1
content-type: application/json

{
  "recipient":"{{$dotenv ADMIN_ADDRESS}}",
  "amount":"1.0"
}

### List FlowToken withdrawals for custody account
GET http://localhost:3000/v1/accounts/{{emulatorCustodyAccount}}/fungible-tokens/flow-token/withdrawals HTTP/1.1
content-type: application/json

### List FUSD withdrawals for custody account
GET http://localhost:3000/v1/accounts/{{emulatorCustodyAccount}}/fungible-tokens/fusd/withdrawals HTTP/1.1
content-type: application/json

### Get FlowToken withdrawal details for custody account
GET http://localhost:3000/v1/accounts/{{emulatorCustodyAccount}}/fungible-tokens/flow-token/withdrawals/<transaction_id> HTTP/1.1
content-type: application/json

### Get FlowToken deposits for custody account
GET http://localhost:3000/v1/accounts/{{emulatorCustodyAccount}}/fungible-tokens/flow-token/deposits HTTP/1.1
content-type: application/json

### Get FlowToken deposit details for custody account
GET http://localhost:3000/v1/accounts/{{emulatorCustodyAccount}}/fungible-tokens/flow-token/deposits/<transaction_id> HTTP/1.1
content-type: application/json

### Setup FUSD on emulator for custody account
POST http://localhost:3000/v1/accounts/{{emulatorCustodyAccount}}/fungible-tokens/fusd HTTP/1.1
content-type: application/json
